### PR TITLE
Prune out-of-date docs

### PR DESCRIPTION
**Pull request by netzzer**
KCS and blogs with same content. Should we look to decomm these docs as well?
```
Disconnected env install - https://access.redhat.com/articles/5172131
Local disk install - https://www.openshift.com/blog/deploying-openshift-container-storage-using-local-devices
Live disk replacement - https://access.redhat.com/solutions/4982091
```
Also, would like to tag current state of master before PR is merged so content can be still be reached.

### CODE REVIEW

**Review by mulbc — COMMENTED** [review]
lgtm - Added some more now stale images that can be removed

**Comment by mulbc** [comment]
We can add the tag once the PR is merged, I'll use the commit just before this PR for that

**Review by netzzer — COMMENTED** [review]
Please leave any images with *CephCluster* or *CephOSD*

**Comment by mulbc** [comment]
> Please leave any images with _CephCluster_ or _CephOSD_

So these images?

```
OCS-OCP-CephCluster-Alerts.png
OCS-OCP-CephClusterCriticallyFull.png
OCS-OCP-CephClusterNearFull.png
OCS-OCP-CephClusterReadOnly.png
OCS-OCP-CephOSD-Alerts.png
```

Are these all the images? You can see a list of files I touched here:
https://github.com/red-hat-storage/ocs-training/pull/195/files

**Comment by netzzer** [comment]
> > Please leave any images with _CephCluster_ or _CephOSD_
> 
> So these images?
> 
> ```
> OCS-OCP-CephCluster-Alerts.png
> OCS-OCP-CephClusterCriticallyFull.png
> OCS-OCP-CephClusterNearFull.png
> OCS-OCP-CephClusterReadOnly.png
> OCS-OCP-CephOSD-Alerts.png
> ```
> 
> Are these all the images? You can see a list of files I touched here:
> https://github.com/red-hat-storage/ocs-training/pull/195/files

Yes, these are the images I would like to keep for creating new content

**Pull request merged**
