### PR TITLE
4.7 additional features

### PR DESCRIPTION
**Pull request by jeanchlopez**
Rework of module plus addition of 4.8 data segregation

### CODE REVIEW

**Comment by mulbc** [comment]
Instead of adding yet another very long doc, could we split this up into separate docs? We can keep that under a `Development Preview` title in the left ToC that is usually unexpanded

What do you think of that?

**Comment by jeanchlopez** [comment]
> Instead of adding yet another very long doc, could we split this up into separate docs? We can keep that under a `Development Preview` title in the left ToC that is usually unexpanded
> 
> What do you think of that?

Yes I can do that and have 3 documents. One for the head and one for each release (4.7 and 4.8) so we can add some in the future if we need.

Would that work for you this way?

**Comment by mulbc** [comment]
I actually thought we would do one doc for each feature - do you think that's too much?

**Comment by jeanchlopez** [comment]
I can do that too. I don't really care. It was just that this way we would easily keep track of what DP feature was in what release rather than having to figure out from a single file that would have no reference to which version it belongs. 

I am open. If you see real benefits to one file per feature I'll do.

**Pull request closed without merging**
